version: '3'
services:
  ranger-db:
    build:
      context: .
      dockerfile: Dockerfile.ranger-oracle
      args:
        - ORACLE_VERSION=${ORACLE_VERSION}
    image: ranger-oracle
    container_name: ranger-oracle
    hostname: ranger-db.example.com
    networks:
      - ranger

networks:
  ranger:
    name: rangernw
